Repository FRONTENDBOOTCAMP-13th/Friday13th, pull requests merged in 2025-03, with the labels that each got.

#10 프리티어 설정 및 하이패스 방지
  .prettierrc.cjs
  index.html
  package-lock.json
  package.json
Labels: ⚙️ settings

#19 test
  index.html
  src/common/a11y.css
  src/common/animation.css
  src/common/base.css
  src/common/best-reset.css
  src/common/login-theme.css
  src/common/mini-reset.css
  src/common/modern-reset.css
  src/common/normalize.css
  src/common/theme.css
  src/components/header.html
  src/css/styles/header.css
Labels: ✅ TEST

#29 new/이미지 파일 생성
  index.html
  public/img/logo.svg
  src/components/main_logo/logo.css
  src/components/main_logo/logo.html
  src/style.css
  vite.config.js
Labels: 📄 NEW

#39 main components make
  index.html
  src/components/main_header/main_header.css
  src/components/main_header/main_header.html
  src/components/main_nav/main_nav.css
  src/components/main_nav/main_nev.html
  src/page/mypage_page/mypage.html
  src/style.css
  vite.config.js
Labels: 🎨 HTML&CSS

#41 3/18 오전 파일 정리
  index.html
  src/components/mypage/mypage_class_registration.css
  src/components/mypage/mypage_class_registration.html
  src/components/mypage/mypage_favorite_products.css
  src/components/mypage/mypage_favorite_products.html
  src/components/mypage/mypage_order_status.css
  src/components/mypage/mypage_order_status.html
  src/components/mypage/mypage_product_management.css
  src/components/mypage/mypage_product_management.html
  src/components/mypage/mypage_qr_scanned_products.css
  src/components/mypage/mypage_qr_scanned_products.html
  src/components/mypage/mypage_recent_store.css
  src/components/mypage/mypage_recent_store.html
  src/components/mypage/mypage_review_write.css
  src/components/mypage/mypage_review_write.html
  src/components/mypage/mypage_smart_estimate.css
  src/components/mypage/mypage_smart_estimate.html
  src/components/mypage/mypage_user_profile.css
  src/components/mypage/mypage_user_profile.html
  src/components/smartphone/smartpone_cardcomponent.css
  src/style.css
  vite.config.js
Labels: ✅ TEST

#47 nav 작업 진행
  index.html
  src/common/modern-reset.css
  src/components/main_nav/main_nav.css
  src/components/main_nav/main_nav.html
  src/components/main_nav/main_nev.html
  src/style.css
Labels: 🎨 HTML&CSS

#56 nav components, main headera 수정
  src/components/main_header/main_header.css
  src/components/main_header/main_header.html
  src/components/main_nav/main_nav.css
  src/components/main_nav/main_nav.html
  src/js/animation.js
  src/main.js
Labels: 💻continue

#76 Frame component
  index.html
  public/assets/icon/angle bracket.svg
  src/components/frame/frame_location.css
  src/components/frame/frame_location.html
  src/components/frame/frame_shopping_cart.css
  src/components/frame/frame_shopping_cart.html
  src/style.css
Labels: 💻continue

#80 header components
  index.html
  public/assets/icon/header_files/client
  public/assets/icon/header_files/icon_frame.svg
  public/assets/icon/header_files/icon_menu.svg
  public/assets/icon/header_files/icon_profile.png
  public/assets/icon/header_files/icon_search.svg
  public/assets/icon/header_files/logo.svg
  public/assets/icon/header_files/main.js
  src/components/login/login_google.css
  src/components/main/header/main_header/main_header.css
  src/components/main/header/main_header/main_header.html
  src/components/main/header/main_nav/main_nav.css
  src/components/main/header/main_nav/main_nav.html
  src/components/main/header/main_nav_pc/main_nav_pc.css
  src/components/main/header/main_nav_pc/main_nav_pc.html
  src/components/main/header/main_search_bar/main_search_bar.css
  src/components/main/header/main_search_bar/main_search_bar.html
  src/components/main_header/main_header.css
  src/components/main_header/main_header.html
  src/page/exhibitions_page/exhibitions_page.html
  src/page/kitchen_page/kitchen_page.html
  src/page/living_page/living_page.html
  src/page/pc_page/pc_page.html
  src/page/tv_page/tv_page.html
  src/style.css
  vite.config.js
Labels: 💻continue

#89 tv page footer 제외
  index.html
  public/assets/icon/tv/selct_color_brown.svg
  public/assets/icon/tv/select_color_bage.svg
  public/assets/icon/tv/select_color_white.svg
  public/assets/icon/tv/select_color_yellow.svg
  public/assets/img/tv/393f8fe5-57b2-4f59-b719-d349cc158907.avif
  public/assets/img/tv/44870455-bf88-4817-9324-7cdf3fdfdd29.avif
  public/assets/img/tv/4636866a-0237-47d4-9cfa-0a6c2513d171.avif
  public/assets/img/tv/5481c452-2313-4d6c-b7ba-ce27ccf49012.avif
  public/assets/img/tv/6af375ba-5d6b-43be-b5cb-62c577294f34.avif
  public/assets/img/tv/6bfc13bf-1872-4afb-a52b-8da87250f1f7.avif
  public/assets/img/tv/75b3519a-5c85-47cb-b32d-d3e8ce6f8756.avif
  public/assets/img/tv/84528bb9-3bce-4272-9add-1b2f37523e15.avif
  public/assets/img/tv/8d5a018b-5cff-495a-b4a4-c4788f16e04e.avif
  public/assets/img/tv/9bbb4d87-4e6a-44a4-8b9b-bdc8539dc979.avif
  public/assets/img/tv/atoz.png
  public/assets/img/tv/atoz.webp
  public/assets/img/tv/tv_banner.png
  src/components/cardcomponent/card_component.css
  src/components/cardcomponent/card_component.html
  src/components/cardcomponent/card_component_button.css
  src/components/cardcomponent/card_component_button.html
  src/components/cardcomponent/card_component_text.css
  src/components/cardcomponent/card_component_text.html
  src/components/cardcomponent/products_nav.css
  src/components/cardcomponent/products_nav.html
  src/components/cardcomponent/products_order.css
  src/components/cardcomponent/products_order.html
  src/components/cardcomponent/smartphone_select_color.css
  src/components/cardcomponent/smartphone_select_color.html
  src/components/main_footer/main_footer.html
  src/components/tv/tv_card_component.css
  src/components/tv/tv_card_component.html
  src/page/search_page/search_page.css
  src/page/search_page/search_page.html
  src/page/tv_page/tv_page.css
  src/page/tv_page/tv_page.html
  src/style.css
Labels: modify

#94 Frame component
  index.html
  public/assets/icon/footer/angle bracket.svg
  public/assets/icon/footer/facebook.svg
  public/assets/icon/footer/instagram.svg
  public/assets/icon/footer/kakao.svg
  public/assets/icon/footer/share.svg
  public/assets/icon/footer/twitter.svg
  public/assets/icon/footer/youtube.svg
  public/assets/icon/frame_payment.svg
  public/assets/icon/frame_slick_next.svg
  public/assets/icon/frame_slick_prev.svg
  public/assets/icon/icon_bold_frame.svg
  public/assets/img/frame/buds3_pro.svg
  public/assets/img/frame/s25.svg
  public/assets/img/frame/watch.svg
  src/components/frame/frame_button.css
  src/components/frame/frame_button.html
  src/components/frame/frame_cart_foot.css
  src/components/frame/frame_cart_foot.html
  src/components/frame/frame_empty_cart.css
  src/components/frame/frame_empty_cart.html
  src/components/frame/frame_payment.css
  src/components/frame/frame_payment.html
  src/components/frame/frame_recommend.css
  src/components/frame/frame_recommend.html
  src/page/frame_page/test.html
  src/style.css
Labels: 💻continue

#96 - kitchen page 제작 ing
  index.html
  public/assets/img/kitchen/39ef7f1d-fe15-4f86-bff7-0376daeb1f06.avif
  public/assets/img/kitchen/refrigerator_banner.png
  src/components/cardcomponent/card_component.css
  src/components/cardcomponent/card_component.html
  src/components/cardcomponent/card_component_text.css
  src/components/cardcomponent/products_order.css
  src/components/smartphone/smartphone_button.css
  src/components/smartphone/smartpone_cardcomponent.css
  src/components/tv/tv_card_component.css
  src/components/tv/tv_card_component.html
  src/page/kitchen_page/kitchen_page.css
  src/page/kitchen_page/kitchen_page.html
  src/page/tv_page/tv_page.css
  src/style.css
Labels: 💻continue

#103 css 폰트 수정
  src/components/mypage/mypage_product_management.css
  src/components/mypage/mypage_qr_scanned_products.css
  src/components/mypage/mypage_recent_store.css
  src/components/mypage/mypage_review_write.css
  src/components/mypage/mypage_smart_estimate.css
  src/components/mypage/mypage_user_profile.css
  src/page/mypage_page/mypage.html
Labels: 💻continue

#104 Login components correction
  src/components/mypage/mypage_class_registration.css
  src/components/mypage/mypage_favorite_products.css
  src/components/mypage/mypage_order_status.css
  src/components/mypage/mypage_product_management.css
  src/components/mypage/mypage_qr_scanned_products.css
  src/components/mypage/mypage_recent_store.css
  src/components/mypage/mypage_review_write.css
  src/components/mypage/mypage_smart_estimate.css
  src/components/mypage/mypage_user_profile.css
  src/page/search_page/search_page.css
Labels: 💻continue

#106 banner 수정. body영역 지우기
  src/common/font.css
  src/common/main-theme.css
  src/common/modern-reset.css
  src/components/main/header/main_nav/main_nav.css
  src/components/main/main_compo/main_banner.css
  src/components/main/main_compo/main_banner.html
  src/components/mypage/mypage_product_management.css
  src/components/mypage/mypage_qr_scanned_products.css
  src/components/mypage/mypage_review_write.css
  src/components/mypage/mypage_smart_estimate.css
  src/components/mypage/mypage_user_profile.css
  src/js/animation.js
  src/main.js
  src/page/main_page/main_page.css
  src/page/mypage_page/mypage.css
  src/page/mypage_page/mypage.html
  src/style.css
Labels: 🐞BUG

#111 login margin값 추가
  src/components/login/login_button.css
  src/components/login/login_google.css
  src/components/login/login_qr.css
  src/components/login/login_qr.html
Labels: modify

#116 Page/livingpage
  index.html
  public/assets/icon/living/Item3.svg
  public/assets/icon/living/Item4.svg
  public/assets/icon/living/Item6.svg
  public/assets/icon/living/item.svg
  public/assets/icon/living/item2.svg
  public/assets/icon/living/item5.svg
  public/assets/img/living/0949b70f-c2f8-45d4-9796-a4c925345466.avif
  public/assets/img/living/1306fba4-943a-42b5-b392-92e86f586894.avif
  public/assets/img/living/27e06cbc-7d1c-4cde-9298-fd4da9c0af1e.avif
  public/assets/img/living/2ccdd0a8-f3e8-4831-8e9d-63c514c25070.avif
  public/assets/img/living/4603f135-94cf-49b4-be54-04e1925c451b.avif
  public/assets/img/living/58a46044-54cc-42af-9d9b-6d06cd42061f.avif
  public/assets/img/living/66a51f8f-deec-408e-96d0-c4a9b6585f8d.avif
  public/assets/img/living/72517688-789a-4100-bf0e-44c614ab5d88.avif
  public/assets/img/living/aa9892ab-0e96-4770-a5fd-45b8d3d9b727.avif
  public/assets/img/living/adver.png
  public/assets/img/living/f323d698-4370-41bf-ae63-d8ec389d18cb.avif
  public/assets/img/living/fb4d2d07-4022-4664-a6d0-8dfd648a8139.avif
  public/assets/img/living/living_banner.png
  src/components/main_footer/main_footer_area2.css
  src/page/kitchen_page/kitchen_page.html
  src/page/living_page/living_page.css
  src/page/living_page/living_page.html
  src/page/smartphone/smartphone_page.html
  src/page/tv_page/tv_page.html
  src/style.css
Labels: ✌️finish

#118 main_banner 완성
  public/assets/icon/header_files/icon-slick-next-compo-wht.svg.svg
  public/assets/icon/header_files/icon-slick-prev-compo-wht.svg.svg
  src/components/main/main_compo/main_banner.css
  src/components/main/main_compo/main_banner.html
  src/js/banner.js
  src/main.js
Labels: ✌️finish

#120 - pc/주변기기 페이지 구현
  index.html
  public/assets/icon/pc/Item.svg
  public/assets/icon/pc/Item2.svg
  public/assets/icon/pc/Item3.svg
  public/assets/icon/pc/dropi.svg
  public/assets/img/pc/027f2402-1b8a-4626-a1b8-1d05b51dc0bd.webp
  public/assets/img/pc/0f1f5e0e-ab70-4b7e-bbf5-4d4a687f5a90.webp
  public/assets/img/pc/1706150a-1352-4874-923c-be8728738953.avif
  public/assets/img/pc/35c085d7-1e44-421d-92d8-bc99684b293c.avif
  public/assets/img/pc/5f31ad44-416a-48a5-8baa-cb0401c16c8e.avif
  public/assets/img/pc/793fa0fd-a9dc-4f80-99d3-9e7513a28ab9.avif
  public/assets/img/pc/7d35cef6-496d-468e-8d3c-174627ee9b7c.avif
  public/assets/img/pc/97cff9b7-a1e5-4747-9191-ea4c2c714ad5.avif
  public/assets/img/pc/eda67de2-17b7-490d-9644-4aa0392778fc.avif
  public/assets/img/pc/pc_banner.png
  public/assets/img/pc/pc_intro.webp
  src/components/cardcomponent/card_component.css
  src/components/cardcomponent/card_component.html
  src/components/cardcomponent/card_component_button.css
  src/components/cardcomponent/card_component_button.html
  src/components/cardcomponent/card_component_text.css
  src/page/pc_page/pc_page.css
  src/page/pc_page/pc_page.html
  src/style.css
Labels: ✌️finish

#122 main_cardimg 컴포넌트 완성
  index.html
  public/assets/img/main/buds_1.png
  public/assets/img/main/buds_pc.png
  public/assets/img/main/s10_1.png
  public/assets/img/main/s10_pc.png
  public/assets/img/main/s25_1.png
  public/assets/img/main/s25_pc.png
  public/assets/img/main/ultra_1.png
  public/assets/img/main/ultra_pc.png
  public/assets/img/main/zflip_1.png
  public/assets/img/main/zflip_pc.png
  src/components/main/main_compo/main_cardimg.css
  src/components/main/main_compo/main_cardimg.html
  src/style.css
  vite.config.js
Labels: ✌️finish

#124 Footer responsive correction
  index.html
  src/components/main_footer/main_footer_area1.css
  src/components/main_footer/main_footer_area1.html
  src/components/main_footer/main_footer_area3.css
  src/components/main_footer/main_footer_final.css
  src/components/main_footer/main_footer_final.html
  src/style.css
Labels: ✌️finish

#125 footer 찐 완성
  src/components/main_footer/main_footer_final.css
Labels: ✌️finish

#127 Main card component
  src/components/main_footer/main_footer_final.html
Labels: ✌️finish

#129 login page 구현
  index.html
  src/components/cardcomponent/card_component_button.css
  src/components/cardcomponent/card_component_button.html
  src/components/login/login_account.css
  src/components/login/login_button.css
  src/components/login/login_button.html
  src/components/login/login_checkbox.css
  src/components/login/login_email.css
  src/components/login/login_google.css
  src/components/login/login_google.html
  src/components/login/login_header.css
  src/components/login/login_header.html
  src/components/login/login_id.css
  src/components/login/login_ment1.css
  src/components/login/login_ment1.html
  src/components/login/login_ment2.css
  src/components/login/loginpage.css
  src/components/login/loginpage.html
  src/page/login_page/loginpage.css
  src/page/login_page/loginpage.html
  src/style.css
Labels: ✌️finish

#130 - smartphone page footer 추가 및 title 변경
  src/page/smartphone/smartphone_page.html
  src/page/tv_page/tv_page.html
Labels: ✌️finish

#131 - tv page footer 추가 및 title 변경
  src/page/tv_page/tv_page.html
Labels: ✌️finish

#133 Mod/page
  src/page/kitchen_page/kitchen_page.html
  src/page/living_page/living_page.html
  src/page/pc_page/pc_page.html
  src/page/tv_page/tv_page.html
Labels: ✌️finish

#134 main_cardpro 오류남
  index.html
  public/assets/img/main/TV영상음향.webp
  public/assets/img/main/TV영상음향large.webp
  public/assets/img/main/가전.webp
  public/assets/img/main/가전_large.webp
  public/assets/img/main/모바일PC.jpg
  public/assets/img/main/모바일pc_large.webp
  public/assets/img/main/스토리.webp
  src/components/main/main_compo/main_cardpro.css
  src/components/main/main_compo/main_cardpro.html
  src/style.css
Labels: 🐞BUG

#136 css 수정 및 화면 디테일 수정 스티키는 실패..
  src/components/frame/frame_cart_foot.css
  src/components/frame/frame_location.css
  src/components/frame/frame_payment.css
  src/components/frame/frame_payment.html
  src/components/frame/frame_recommend.css
  src/page/frame_page/frame_page.html
  src/page/frame_page/test.html
Labels: 💻continue

#138 Putchase1
  public/assets/img/putchase/003b8b04-8e50-479e-af9f-dc7951d3c27d.webp
  public/assets/img/putchase/4ffbbc0e-5d8c-415b-b114-bb26d04ef136.webp
  public/assets/img/putchase/8169d81c-3daf-4131-ab65-b2dd3161adca.webp
  public/assets/img/putchase/9d8db568-bdb6-4f30-9f72-b95a1c41014c.webp
  public/assets/img/putchase/b7813a9b-221c-4102-9c26-d2e0baf207c2.avif
  src/components/putchase/putchase_banner.css
  src/components/putchase/putchase_banner.html
  src/components/putchase/putchase_color.css
  src/components/putchase/putchase_color.html
  src/components/putchase/putchase_memory.css
  src/components/putchase/putchase_memory.html
  src/components/putchase/putchase_method.css
  src/components/putchase/putchase_method.html
  src/components/putchase/putchase_model.css
  src/components/putchase/putchase_model.html
  src/components/putchase/putchase_quantity.css
  src/components/putchase/putchase_quantity.html
  src/components/putchase/putchase_storage.css
  src/components/putchase/putchase_storage.html
  src/page/frame_page/frame_page.css
  src/page/purchase/putchase1.css
  src/page/purchase/putchase1.html
Labels: ✌️finish

#139 Main card components
  src/components/main/main_compo/main_cardpro.css
  src/components/main/main_compo/main_cardpro.html
  vite.config.js
Labels: ✌️finish

#141 - search page 디자인 재수정
  src/components/search/search_menu.css
  src/components/search/search_product.css
  src/components/search/search_product.html
  src/components/search/searchbar.css
  src/components/search/searchbar.html
  src/page/login_page/loginpage.css
  src/page/search_page/search_page.css
  src/page/search_page/search_page.html
Labels: modify

#142 cardcompo 완성
  index.html
  public/assets/img/main/cardcompo1.webp
  public/assets/img/main/cardcompo2.webp
  public/assets/img/main/cardcompo3.avif
  public/assets/img/main/cardcompo4.avif
  public/assets/img/main/cardcompo5.avif
  public/assets/img/main/cardcompo6.avif
  public/assets/img/main/cardcompo7.avif
  public/assets/img/main/cardcompo8.webp
  src/components/main/main_compo/main_cardscroll.css
  src/components/main/main_compo/main_cardscroll.html
  src/style.css
Labels: ✌️finish

#149 - pay page 생성 및 버튼 컴포넌트 수정
  index.html
  public/assets/img/pay/credit-logo-etc.svg
  public/assets/img/pay/credit-logo-hana.svg
  public/assets/img/pay/credit-logo-hyundai.svg
  public/assets/img/pay/credit-logo-kb.svg
  public/assets/img/pay/credit-logo-lotte.svg
  public/assets/img/pay/credit-logo-nh.svg
  public/assets/img/pay/credit-logo-samsung.svg
  public/assets/img/pay/credit-logo-woori.svg
  src/components/pay/payment_method.css
  src/components/pay/payment_method.html
  src/page/pay_page/pay_page.css
  src/page/pay_page/pay_page.html
  src/style.css
Labels: ✌️finish

#151 pay_button 완성
  index.html
  public/assets/icon/pay/arrow.up.svg
  public/assets/icon/pay/arrow_down.svg
  public/assets/icon/pay/arrow_right.svg
  src/components/pay/pay_button.css
  src/components/pay/pay_button.html
  src/style.css
Labels: ✌️finish

#153 Pay components
  src/components/pay/pay_address.css
  src/components/pay/pay_address.html
  src/components/pay/pay_address_find.css
  src/components/pay/pay_address_find.html
  src/components/pay/pay_delivery.css
  src/components/pay/pay_delivery.html
  src/components/pay/pay_orderer.css
  src/components/pay/pay_orderer.html
  src/page/mypage_page/mypage.css
  src/page/mypage_page/mypage.html
Labels: modify

#154 index 정리, vite.config 정리
  index.html
  src/page/frame_page/frame_page.html
  vite.config.js
Labels: ✌️finish

#165 이미지 경로 수정
  public/assets/img/main/home.webp
  public/assets/img/main/home_large.webp
  public/assets/img/main/mopc.jpg
  public/assets/img/main/mopc_large.webp
  public/assets/img/main/story.webp
  public/assets/img/main/tv_m.webp
  public/assets/img/main/tv_m_large.webp
  src/components/main/main_compo/main_cardpro.css
  src/components/main/main_compo/main_cardpro.html
  src/components/main_footer/main_footer_final.html
Labels: modify

#172 - page별 title 수정
  src/components/search/search_product.css
  src/page/login_page/loginpage.html
  src/page/main_page/main_page.html
  src/page/main_page/main_page_reset.html
  src/page/purchase/putchase1.html
  src/page/search_page/search_page.html
Labels: modify

#177 mypage css 수정
  src/page/mypage_page/mypage.css
  src/page/mypage_page/mypage.html
Labels: modify

#185 mypage_page css 수정
  src/components/mypage/mypage_class_registration.css
  src/components/mypage/mypage_user_profile.css
  src/style.css
Labels: modify

#194 - page banner 사이즈 수정 완
  README.md
  src/page/kitchen_page/kitchen_page.css
  src/page/living_page/living_page.css
  src/page/pc_page/pc_page.css
  src/page/pc_page/pc_page.html
  src/page/smartphone/smartphone_page.css
Labels: ✌️finish
